services:
  # db:
  #   container_name: app-postgres
  #   image: postgres
  #   restart: no
  #   environment:
  #     POSTGRES_USER: db
  #     POSTGRES_PASSWORD: db
  #     POSTGRES_DB: app-db
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./data/postgres:/var/lib/postgresql/data

  mongodb:
    image: mongo
    container_name: app-mongodb
    # command: [--auth]
    restart: no
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - 27017:27017
    expose:
      - 27017

  redis:
    image: redis
    container_name: app-redis
    # command: redis-server --requirepass test
    restart: no
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
    expose:
      - 6379

  prometheus:
    container_name: app-prometheus
    image: prom/prometheus:latest
    restart: no
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  grafana:
    container_name: app-grafana
    image: grafana/grafana:latest
    restart: no
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana

  tempo:
    container_name: app-tempo
    image: grafana/tempo:latest
    restart: no
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./data/tempo:/tmp/tempo
    ports:
      - "3200:3200" # tempo
      - "4318:4318" # otlp http

