services:
  # db:
  #   container_name: app-postgres
  #   image: postgres
  #   restart: no
  #   environment:
  #     POSTGRES_USER: db
  #     POSTGRES_PASSWORD: db
  #     POSTGRES_DB: app-db
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./data/postgres:/var/lib/postgresql/data

  mongodb:
    image: mongo
    container_name: app-mongodb
    # command: [--auth]
    restart: no
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - 27017:27017
    expose:
      - 27017

  redis:
    image: redis
    container_name: app-redis
    # command: redis-server --requirepass test
    restart: no
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
    expose:
      - 6379

